-- 指数专题表（index_basic、日/周/月 K、成分权重）
-- 执行前请确认库名与字符集与项目一致

CREATE TABLE IF NOT EXISTS index_basic (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  ts_code VARCHAR(32) NOT NULL,
  name VARCHAR(128) NULL,
  fullname VARCHAR(255) NULL,
  market VARCHAR(16) NULL,
  publisher VARCHAR(64) NULL,
  index_type VARCHAR(64) NULL,
  category VARCHAR(64) NULL,
  base_date DATE NULL,
  base_point DECIMAL(16,4) NULL,
  list_date DATE NULL,
  weight_rule VARCHAR(255) NULL,
  description TEXT NULL,
  exp_date DATE NULL,
  data_source VARCHAR(32) NOT NULL DEFAULT 'tushare',
  synced_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_index_basic_ts (ts_code),
  KEY idx_index_basic_market (market)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS index_daily_bar (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  index_code VARCHAR(32) NOT NULL,
  trade_date DATE NOT NULL,
  open DECIMAL(12,4) NULL,
  high DECIMAL(12,4) NULL,
  low DECIMAL(12,4) NULL,
  close DECIMAL(12,4) NULL,
  ma5 DECIMAL(16,8) NULL,
  ma10 DECIMAL(16,8) NULL,
  ma20 DECIMAL(16,8) NULL,
  ma60 DECIMAL(16,8) NULL,
  macd_dif DECIMAL(16,8) NULL,
  macd_dea DECIMAL(16,8) NULL,
  macd_hist DECIMAL(16,8) NULL,
  prev_close DECIMAL(12,4) NULL,
  change_amount DECIMAL(12,4) NULL,
  pct_change DECIMAL(10,4) NULL,
  volume DECIMAL(20,2) NULL,
  amount DECIMAL(20,2) NULL,
  amplitude DECIMAL(10,4) NULL,
  data_source VARCHAR(32) NOT NULL DEFAULT 'tushare',
  sync_batch_id VARCHAR(64) NULL,
  synced_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_index_daily_code_date (index_code, trade_date),
  KEY idx_index_daily_trade_date (trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS index_weekly_bar (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  index_code VARCHAR(32) NOT NULL,
  trade_week_end DATE NOT NULL,
  open DECIMAL(12,4) NULL,
  high DECIMAL(12,4) NULL,
  low DECIMAL(12,4) NULL,
  close DECIMAL(12,4) NULL,
  ma5 DECIMAL(16,8) NULL,
  ma10 DECIMAL(16,8) NULL,
  ma20 DECIMAL(16,8) NULL,
  ma60 DECIMAL(16,8) NULL,
  macd_dif DECIMAL(16,8) NULL,
  macd_dea DECIMAL(16,8) NULL,
  macd_hist DECIMAL(16,8) NULL,
  change_amount DECIMAL(12,4) NULL,
  pct_change DECIMAL(10,4) NULL,
  volume DECIMAL(20,2) NULL,
  amount DECIMAL(20,2) NULL,
  data_source VARCHAR(32) NOT NULL DEFAULT 'tushare',
  sync_batch_id VARCHAR(64) NULL,
  synced_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_index_weekly_code_end (index_code, trade_week_end),
  KEY idx_index_weekly_end (trade_week_end)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS index_monthly_bar (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  index_code VARCHAR(32) NOT NULL,
  trade_month_end DATE NOT NULL,
  open DECIMAL(12,4) NULL,
  high DECIMAL(12,4) NULL,
  low DECIMAL(12,4) NULL,
  close DECIMAL(12,4) NULL,
  ma5 DECIMAL(16,8) NULL,
  ma10 DECIMAL(16,8) NULL,
  ma20 DECIMAL(16,8) NULL,
  ma60 DECIMAL(16,8) NULL,
  macd_dif DECIMAL(16,8) NULL,
  macd_dea DECIMAL(16,8) NULL,
  macd_hist DECIMAL(16,8) NULL,
  change_amount DECIMAL(12,4) NULL,
  pct_change DECIMAL(10,4) NULL,
  volume DECIMAL(20,2) NULL,
  amount DECIMAL(20,2) NULL,
  data_source VARCHAR(32) NOT NULL DEFAULT 'tushare',
  sync_batch_id VARCHAR(64) NULL,
  synced_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_index_monthly_code_end (index_code, trade_month_end),
  KEY idx_index_monthly_end (trade_month_end)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS index_weight (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  index_code VARCHAR(32) NOT NULL,
  con_code VARCHAR(32) NOT NULL,
  trade_date DATE NOT NULL,
  weight DECIMAL(12,4) NOT NULL,
  synced_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_index_weight (index_code, con_code, trade_date),
  KEY idx_index_weight_index (index_code),
  KEY idx_index_weight_td (trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
