-- 006-技术指标扩展：为日/周/月 K 线表增加均线与 MACD 列（与 data-model.md 一致）
-- 执行前请备份；MySQL 8+

ALTER TABLE stock_daily_bar
  ADD COLUMN ma5 DECIMAL(16, 8) NULL COMMENT 'SMA5(close)' AFTER close,
  ADD COLUMN ma10 DECIMAL(16, 8) NULL AFTER ma5,
  ADD COLUMN ma20 DECIMAL(16, 8) NULL AFTER ma10,
  ADD COLUMN ma60 DECIMAL(16, 8) NULL AFTER ma20,
  ADD COLUMN macd_dif DECIMAL(16, 8) NULL AFTER ma60,
  ADD COLUMN macd_dea DECIMAL(16, 8) NULL AFTER macd_dif,
  ADD COLUMN macd_hist DECIMAL(16, 8) NULL AFTER macd_dea;

ALTER TABLE stock_weekly_bar
  ADD COLUMN ma5 DECIMAL(16, 8) NULL COMMENT 'SMA5(close)' AFTER close,
  ADD COLUMN ma10 DECIMAL(16, 8) NULL AFTER ma5,
  ADD COLUMN ma20 DECIMAL(16, 8) NULL AFTER ma10,
  ADD COLUMN ma60 DECIMAL(16, 8) NULL AFTER ma20,
  ADD COLUMN macd_dif DECIMAL(16, 8) NULL AFTER ma60,
  ADD COLUMN macd_dea DECIMAL(16, 8) NULL AFTER macd_dif,
  ADD COLUMN macd_hist DECIMAL(16, 8) NULL AFTER macd_dea;

ALTER TABLE stock_monthly_bar
  ADD COLUMN ma5 DECIMAL(16, 8) NULL COMMENT 'SMA5(close)' AFTER close,
  ADD COLUMN ma10 DECIMAL(16, 8) NULL AFTER ma5,
  ADD COLUMN ma20 DECIMAL(16, 8) NULL AFTER ma10,
  ADD COLUMN ma60 DECIMAL(16, 8) NULL AFTER ma20,
  ADD COLUMN macd_dif DECIMAL(16, 8) NULL AFTER ma60,
  ADD COLUMN macd_dea DECIMAL(16, 8) NULL AFTER macd_dif,
  ADD COLUMN macd_hist DECIMAL(16, 8) NULL AFTER macd_dea;
